### ISSUE TITLE
Make Profiles more pluggable, move Profile implementation to OCIProfile

### ISSUE THREAD

**Issue by riyazdf** [docker/libentitlement#22]
From discussion with @n4ss: the current code for profiles is OCI specific, and so it should move to a `OCIProfile` that implements a common `Profile` interface.

For other platforms with different profile formats, folks can plug in to the `Profile` interface with platform-specific implementations.

**Comment by n4ss** [comment]
Implemented this here: https://github.com/n4ss/libentitlement/commits/pluggable-profile

It's currently on top of the branch for the #25 PR so I'll submit it as a PR when this gets merged.

**Comment by n4ss** [comment]
Closed by https://github.com/docker/libentitlement/pull/30.
