### ISSUE TITLE
Follow Go style guidelines for package exports

### ISSUE THREAD

**Issue by stevvooe** [docker/libentitlement#28]
I was just taking a quick peak through and noticed a few odd style choices in the package exports:

- `Oci` -> `OCI`: OCI is an initialism and should be capitalized
- The package names shouldn't have an underscore (probably rename it to `securityprofile`)

Check out https://github.com/golang/go/wiki/CodeReviewComments for the full set of guidelines.

I can send a PR if that is easier, but it might help to adopt these as project standards.

**Comment by n4ss** [comment]
Thanks a lot for the input! Still relatively new to Golang so that helps :)

**Comment by stevvooe** [comment]
@n4ss We can probably close this.
